//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: login.proto
namespace ServerProtos
{
	[global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SendConnector")]
	public partial class SendConnector : global::ProtoBuf.IExtensible
  {
		public SendConnector() {}
    
    	private int _code;
		[global::ProtoBuf.ProtoMember(1, IsRequired = true, Name= @"code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
		public int code
	    {
			get { return _code; }
			set { _code = value; }
		}
	    private string _host;
	    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name= @"host", DataFormat = global::ProtoBuf.DataFormat.Default)]
	    public string host
	        {
			get { return _host; }
			set { _host = value; }
	    }

		private int _port;
		[global::ProtoBuf.ProtoMember(3, IsRequired = true, Name= @"port", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
		public int port
		{
			get { return _port; }
			set { _port = value; }
		}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
 
  
}